#!/usr/bin/env bash
# script that installs nginx, configure a new Ubuntu machine
# and then print "Hello World"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
