#!/usr/bin/env bash
# Script that configures Nginx to web02

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
config_file="/etc/nginx/sites-available/default"
hostname=$(hostname)
sudo sed -i "/listen \[::\]:80 default_server;/ a \    add_header X-Served-By \"$hostname\";" "$config_file"
sudo service nginx restart

echo "Nginx configured with custom header X-Served-By: $hostname"
