#!/usr/bin/env bash
# displays "To infinity and beyond" indefinitely but kill it with ctrl+c
# between each iteration it added of loop "sleep 2"

while true
do
  echo "To infinity and beyond"
  sleep 2
done

