#!/usr/bin/env bash
# loop 10 times it displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations


k=0
while [ $k -lt 10 ]
do
    if [ $k -eq 3 ]
    then
        echo "bad luck"
    elif [ $k -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((k++))
done

