#!/usr/bin/env bash
# displays 20 loops 4 bad luck from china, 9 bad luck for japan
# 17 bad luck for Italy


a=1
while [ $a -le 20 ]
do
    echo "$a"
    case $a in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
    esac
    (( a++ ))
done

